# Generated by Django 3.2.3 on 2021-05-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='FireAndIce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=55)),
                ('date', models.DateField()),
            ],
        ),
    ]
