# Generated by Django 3.2.3 on 2021-05-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_fireandice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fireandice',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
